# Generated by Django 3.2.3 on 2023-08-25 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 25, 12, 55, 14, 741444), null=True)),
            ],
        ),
    ]
